theme = "apr"
baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Ataias"

#This isn't configured yet
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
  initialyear = "2016"

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/ataiasreis"
    github   = "https://github.com/ataias"
    googleplus  = "https://plus.google.com/109223219327789162075"
