theme = "apr"
baseurl = "http://192.168.2.6/"
languageCode = "en-us"
title = "Ataias"

#This isn't configured yet
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
  initialyear = "2016"
  Blog = "Blog"
  About = "About"

# Accounts
[social]
    twitter  = "ataiasreis"
    github   = "ataias"
    googleplus  = "109223219327789162075"
    facebook = "ataiasreis"
    linkedin = "ataias-pereira-reis-25448487"
    email = "ataias@outlook.com"
    stackoverflow = "2304697/ataias-reis"

[taxonomies]
  tag = "tags"
